### ISSUE TITLE
Problem inserting a record

### ISSUE THREAD

**Issue by ebrahimiali9005** [vdm-io/Joomla-Component-Builder#342] opened 2018-09-21 06:44 UTC
Hello
Sometimes after creating a new record in a video, the id will be added to the two. For example, a new identifier of 10 must be a new ID 11
  This problem occurs sometimes.
Also, I encountered this problem when copying fields
If the database responds late, will you try to insert a new record?
Thank you for checking.

**Comment by peterpetrov** [comment] 2018-09-21 06:50
Hello @ebrahimiali9005. Thank you for posting your issue here. I would like to assist you on how you can provide us with proper information so we (the JCB community) can assist you.  

First please use that form for when submitting bugs that you find.

**Steps to reproduce the issue

Expected result

Actual result


System information (as much as possible)
OS Name & Version: 
MySql Version: 
Apache Version: 
PHP Version: 
Joomla Version: 
JCB Version: 
Browser:

Additional comments** 


It is very important that you describe the exact steps to reproduce the issue as we need to verify that is an actual bug. So please use that form and let us know what the issue is.

Also try to post one issue at a time - currently you have two. The second one is not related at all to JCB so i suggest you try to find why your database performs slower on another post board.

**Comment by Llewellynvdm** [comment] 2018-09-29 00:52
We will close this issue, if you need any further help, just comment on this issue again, and we will respond. Remember to give more details, thanks!

**Closed by Llewellynvdm** 2018-09-29 00:52 UTC
