### ISSUE TITLE
routing not work as expeced

### ISSUE THREAD

**Issue by studiosacchetti** [vdm-io/Joomla-Component-Builder#448] opened 2019-07-22 14:25 UTC
### Steps to reproduce the issue
 this is my first experience with this  component so i'm trying  to understand how does it work, 
like create new site view and delete it but it seem that route it's not generated correclly after that.
for example in this code case house is repeated twice.  i'm using v2.9.21

```
public function parse(&$segments)
	{		
		$count = count($segments);
		$vars = array();
		
		//Handle View and Identifier
		switch($segments[0])
		{
			case 'feature':
				$vars['view'] = 'feature';
				if (is_numeric($segments[$count-1]))
				{
					$vars['id'] = (int) $segments[$count-1];
				}
				break;
			case 'category':
				$vars['view'] = 'category';
				if (is_numeric($segments[$count-1]))
				{
					$vars['id'] = (int) $segments[$count-1];
				}
				break;
			case 'request':
				$vars['view'] = 'request';
				if (is_numeric($segments[$count-1]))
				{
					$vars['id'] = (int) $segments[$count-1];
				}
				break;
			case 'house':
				$vars['view'] = 'house';
				if (is_numeric($segments[$count-1]))
				{
					$vars['id'] = (int) $segments[$count-1];
				}
				break;
			case 'houses':
				$vars['view'] = 'houses';
				if (is_numeric($segments[$count-1]))
				{
					$vars['id'] = (int) $segments[$count-1];
				}
				elseif ($segments[$count-1])
				{
					$id = $this->getVar('house', $segments[$count-1], 'alias', 'id');
					if($id)
					{
						$vars['id'] = $id;
					}
				}
				break;
			case 'house':
				// default script in switch for this view
				$vars['view'] = 'house';
				if (is_numeric($segments[$count-1]))
				{
					$vars['id'] = (int) $segments[$count-1];
				}
				elseif ($segments[$count-1])
				{
					$id = $this->getVar('house', $segments[$count-1], 'alias', 'id');
					if($id)
					{
						$vars['id'] = $id;
					}
				}
				break;
			case 'category':
				$vars['view'] = 'category';
				if (is_numeric($segments[$count-1]))
				{
					$vars['id'] = (int) $segments[$count-1];
				}
				elseif ($segments[$count-1])
				{
					$id = $this->getVar('house', $segments[$count-1], 'alias', 'id');
					if($id)
					{
						$vars['id'] = $id;
					}
				}
				break;
			case 'housetwo':
				// default script in switch for this view
				$vars['view'] = 'housetwo';
				if (is_numeric($segments[$count-1]))
				{
					$vars['id'] = (int) $segments[$count-1];
				}
				elseif ($segments[$count-1])
				{
					$id = $this->getVar('housetwo', $segments[$count-1], 'alias', 'id');
					if($id)
					{
						$vars['id'] = $id;
					}
				}
				break;
		}

		return $vars;
	} 

```

**Comment by Llewellynvdm** [comment] 2019-07-23 01:36
I think it is due to having an admin view with the name `house` and a site view with the same name `house` or even two site-views with the same name and so the conflict will be resolved by changing the name of the site view to `housing` or something that does not conflict with the back-end/admin or other site view name.

Then about removing site-views, and adding them again... and removing them... well this will cause you some pain indeed and this since JCB does automated updating via mysql. So to understand how all that work you need to [watch these tutorials](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fgithub.com%2Fvdm-io%2FJoomla-Component-Builder%2Fwiki+automated+database+updates) surrounding that.

There is a hello world extended tutorial, which really helps you see the normal path of development, if you have watch that... then great, but hey there is so much more.

So the routing can be over written via an area in the dynamicGet, and yes again there is a tutorial about that.

The fastest way to find answers, if you do not have the time to watch all those boring tutorials is via a google search of the JCB wiki pages, like this: `site:https://github.com/vdm-io/Joomla-Component-Builder/wiki routing`
![image](https://user-images.githubusercontent.com/5607939/61675171-7fa61080-acf7-11e9-985b-f58d7b843d23.png)

Once you understand JCB, it is like a dream come true... so press on you will not be sorry!

**Comment by Llewellynvdm** [comment] 2019-07-23 20:49
I assume the issue is resolved, just comment here if you need more help with this :+1:

**Closed by Llewellynvdm** 2019-07-23 20:49 UTC
