### ISSUE TITLE
Unpublished/Trashed Layouts keep being generated and can not be removed

### ISSUE THREAD

**Issue by pjdevries** [vdm-io/Joomla-Component-Builder#389] opened 2019-03-04 13:34 UTC
### Steps to reproduce the issue
Create a Layout.
Compile and install component.
Make sure the layout file exists and then delete it.
Unpublish or Trash the Layout.
Compile and install component.

### Expected result
The layout file should no longer exist.

### Actual result
The layout file is still there.

### System information (as much as possible)
- OS Name & Version: JCB 2.9.11
- MySql Version: 5.7.21
- Apache Version: 2.4.33
- PHP Version: 7.2.4
- Joomla Version: 3.9.3
- JCB Version: JCB 2.9.11
- Browser: FireFox

### Additional comments
Obviously layouts should not be generated when Unpublished or Trashed. Additionally, the JCB Layout management view has no possibility to permanently delete Trashed layouts.

**Comment by Llewellynvdm** [comment] 2019-03-04 13:51
Layouts are added based on being in the a site view, and template or in another layouts. The publishing status does not remove it from component, just from seeing it in the list of available layouts to be added in those above mentioned areas. So to have it removed, you need remove it from the areas where it is in use manually.

We have had internal debates about this, and the conclusion was since the site views are really custom build and not so automated as the back-end we did not want to add the feature of auto removal of layouts and templates but stick to the manual expected behavior.

Then like all Joomla core components to completely delete a item, you must select trashed status in the list view filters, and then only will you see a delete button in the toolbar. This is Joomla's way of protecting mistaken deletions.

**Comment by pjdevries** [comment] 2019-03-04 14:55
First of all I have to admid having made w wrong observation. I looked for the filter in the wrong place, so I thought I could not delete the layout completely. Apologies for that.

I don't quite agree with the function of the unpublished state though. In Joomla! itself, unpublished usually means an item won't show up in the frontend of the site. It seems to me we are talking about that in this case :)

One of the things I'm struggling with, is all that custom code _within_ JCB. Writing code with JCB itself is not really an option. So the only realistic way to produce that that code, is writing, testing and debugging it in an installed component and then copy & paste it back into JCB. Not only a bit cumbersome, but also error prone. When you forget the copy & paste, you may loose substantial changes.

I prefer to keep the custom code out of JCB as much as possible. Have it completely in files within the custom folder, while maintaining as little code as necessary to activate that custom code in JCB itself. With all the magic that's going on, that's difficult and causes unwanted side effects. 

For the most part I agree with the fact that site view are custom build, more often than not. Although I love the automatically generated edit views :) But since most other are custom build, it might be worth considering to remove all magic from the template/layout generation process all together. So no automagical generation of layout based on the occurance of a layout name PHP code in the Site View. Leave that up to the responsibility of the developer and allow him/her full control.

**Comment by Llewellynvdm** [comment] 2019-03-04 15:46
Okay we are not seeing this in the same way, which is okay with me :+1:

There is no automagical generation of layouts and stuff. It only gets generated because you place the code like `<?php echo JLayoutHelper::render('layoutname', $this->item); ?>` in a site view or in a template or in another layout. So should you like it removed, just remove that string from that area you placed it, no confusion there. Secondly if you do not longer want other on your team to use the layout unpublish it and it is removed from the list of available layouts.

Since if you don't remove it manually from the areas, you will anyway break your component. Joomla will try to get the layout because of that code string `<?php echo JLayoutHelper::render('layoutname', $this->item); ?>`, and then it is not there and therefore break and give errors.

So you added it manually and possible some other HTML around it or even some logic, so if you want it removed, just unpublishing is not the smart choice, bot opening the area and manually removing it and adapting your own HTML and logic, is what seems most consistent with the workflow and stability.

Then about custom code in JCB, well that is not even close to my experience. I am hardly ever having struggles editing code in the IDE and then moving it to JCB, I write it up in JCB, compile, and if it does not work I edit it until it works, then simply copy it over, done. Works like a breeze seeing I can then go a step up and move it to the global custom code area (using customcode placeholders) and start using it all over in other components, meanwhile editing it all in one place. So my experience it to use JCB custom code placeholder all over the place in excess.

**Comment by pjdevries** [comment] 2019-03-04 16:22
I have the distinct feeling we're having misunderstanding here. Not your fault. Maybe partly because English is not my native language. Probably mostly because I'm very bad in putting into words what I mean. Even in my native language :(

Let's leave it at this.

**Comment by Llewellynvdm** [comment] 2019-03-04 17:05
Okay, well if I misunderstood you... so be it, my native language is also not English :) but just to make sure you understand me.

To add a layout to a component we do the following:
![image](https://user-images.githubusercontent.com/5607939/53748397-f3ad5c80-3ead-11e9-8bac-4eb8af06fce0.png)
We add the `<?php echo JLayoutHelper::render('companydetails', $item); ?>` to a site view, or template or even another layout as shown above. 

Then around that we have some HTML
```php
<?php if (isset($this->items) && [[[component]]]Helper::checkArray($this->items)): ?>
<!-- This is the modal -->
<div id="combine" class="uk-modal">
    <div class="uk-modal-dialog">
        <a class="uk-modal-close uk-close"></a>
        <h3><?php echo JText::_('Select Companies to Combine'); ?><h3>
        <p data-uk-margin>
        <?php foreach ($this->items as $item): ?>
	         <button id="combined_<?php echo $item->id; ?>" class="uk-button uk-margin-small-top" onclick="setCombined(<?php echo $item->id; ?>)" status="0"><i id="icon_<?php echo $item->id; ?>" class='uk-icon-toggle-off uk-hidden-small'></i> <?php echo $item->name; ?></button>
       <?php endforeach;?>
        </p><input id="combined" value="" type="hidden"><div class="uk-modal-footer"><button class="uk-button uk-button-primary" type="button" onclick="combine()"><?php echo JText::_('View Combined Results'); ?></button></div>
    </div>
</div>
<div class="uk-accordion uk-width-1-1" data-uk-accordion="{showfirst:false}">
	<?php foreach ($this->items as $item): ?>
		<h3 class="uk-accordion-title"><i class='uk-icon-building-o uk-hidden-small'></i> <?php echo $item->name; ?><span class="uk-hidden-small"> <em>(<?php echo ($item->department ==1) ? JText::_('Basic Profile') : JText::_('Advanced Profile'); ?>)</em></span><span class="uk-visible-small"> <em>(<?php echo ($item->department ==1) ? 'B' : 'A'; ?>)</em></span></h3>
		<div class="uk-accordion-content">
			<?php echo JLayoutHelper::render('companydetails', $item); ?>
		</div>
	<?php endforeach; ?>
</div>
<?php endif; ?>
```
That works along side the `<?php echo JLayoutHelper::render('companydetails', $item); ?>` that is being loaded. So all I am saying is just unpublishing the layout will not work in removing it from this area in a stable and expected way. Best practice it to manually remove it, then also to adapt the HTML and logic surrounding it. Doing this will stop JCB from generating the layout.

So if I no longer want `<?php echo JLayoutHelper::render('companydetails', $item); ?>` in my component I just remove `<?php echo JLayoutHelper::render('companydetails', $item); ?>` and then it is removed. Should you just unpublish it (expecting it will no longer be generated), the string `<?php echo JLayoutHelper::render('companydetails', $item); ?>` is still in the component (part of the code), and Joomla will still try to load it, and since it can't find it we will end up with an error.

The other idea to if unpublish remove the string everywhere it is used in all areas, will firstly result in the surrounding code being left without the idea that something changed. Then most importantly, if you publish it again, JCB has no way of knowing where to add it back in... so you thinking it will just be added back in again will not happen. So all of that behavior will be even more confusing. Keeping the task manual in this case is the best solution to a stable and expected outcome, and really giving the developer full control.

In sort if the layout is called upon in the code of any site view, template or another layout, then JCB will add it to the component, if it is not called upon, then it will not be added.

So I will close this issue seeing that the current implementation is most effective. Realizing that we may be missing each other and that you could be speaking about something completely other to what I am pointing. If this is the case, you are more then welcome to continue explaining your issue, and should we see and realize the actual, we will open it again :+1:

**Closed by Llewellynvdm** 2019-03-04 17:05 UTC
