### ISSUE TITLE
defualt value none for database fields

### ISSUE THREAD

**Issue by derakhshana** [vdm-io/Joomla-Component-Builder#602] opened 2020-09-19 23:20 UTC
### Steps to reproduce the issue

When set none for default value for a filed in database tap
### Expected result
'column1' INT NULL,

### Actual result
'column1' INT NULL DEFAULT '',

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 3.9.20
- JCB Version: 2.11.4
- Browser: 

### Additional comments
we expect that when set none for default value it means that no DEFAULT keyword will not appear in the sql install script for that filed but the DEFAULT ''  is inserted!

**Comment by Llewellynvdm** [comment] 2020-09-24 22:17
Let see, yes that seems to be the case. What we can try and do to please as many as possible. Se will need to look at the expected behavior, and then see if we can change things not to break that.

So I initially said if field is `NOT NULL` and default of none, then we give it a `DEFAULT ''` which is the expected behavior. But you are saying it is `NULL` and then I agree it should not add a empty default, since no value should be `NULL`. Lets see if I can change that.

Would you agree with making only that change?

**Comment by Llewellynvdm** [comment] 2020-10-06 23:09
Okay I am looking over the code, and I am wondering if you can do some tests for me?

So on line [10009](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/compiler/e_Interpretation.php#L10009) we are checking if the default is "EMPTY" and then adding the null switch. So this EMPTY is set in the Other value like this:
![image](https://user-images.githubusercontent.com/5607939/95269309-6ffde380-0839-11eb-92db-749de3aa8003.png)

Can you try this and see if it resolves your issue.

**Comment by Llewellynvdm** [comment] 2020-10-09 13:06
I am closing this, should the solution not work for you, just bump the closed issue again.

**Closed by Llewellynvdm** 2020-10-09 13:06 UTC
