### ISSUE TITLE
Import Language File is broken

### ISSUE THREAD

**Issue by marcorensch** [vdm-io/Joomla-Component-Builder#588] opened 2020-08-14 15:36 UTC
### Steps to reproduce the issue
Export your Languages.xls from JCB
Do your translations
Try to Import the edited file

### Expected result
Successfull import

### Actual result
You will facing the error : 1062 Duplicate entry '*first_id_of_set*' for key 'PRIMARY' and the import stops

### System information (as much as possible)
- OS Name & Version: MacOS Catalina (MAMP)
- MySql Version:  5.7.26
- Apache Version: n/A
- PHP Version: 7.4.2
- Joomla Version: 3.9.20
- JCB Version: 2.11.4 
- Browser: Firefox 78.0.2

### Additional comments
Done the steps as described in your video https://www.youtube.com/watch?v=q5NwKGnOHoQ&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE

**Comment by Llewellynvdm** [comment] 2020-08-16 22:33
I am trying to reproduce the issue, but with no success. I know we did fix issues in this area with the last update, and in all my test things worked as expected. But it could be an edge case that I have not encountered. Would you mind sharing a small part of your file, so I can test it some how... not sure how, since I need the strings in my system before to actually get the same outcome. So is it possible to record all our steps, and or, provide me with a generic component that cause the same error.

**Comment by marcorensch** [comment] 2020-08-17 06:13
Thats strange, I've tried it now with another JCB installation and another of mine extensions on another host (same dev platform on my mac - I've created dedicated Hosts for each JCB component that I develop) and the same error occurs. I will now test to create a totaly new one with the latest version of JCB (the others where updated) and try to import the JCB Package and try then to do a translation export / import. I'll keep you updated.

**Comment by Llewellynvdm** [comment] 2020-08-19 01:30
This is not errors, but notices. You will see that the Joomla Component with ID 25 is not in the system, and yet the language string was linked to this component in the previous system. So JCB is just decoupling it here, and giving you the notice.

This is why I added a new switch in the last update of JCB, that will allow me to export all the JCB demo packages without the language strings. You can see this switch in the Global Options under the Global tab:
![image](https://user-images.githubusercontent.com/5607939/90581047-96ed5100-e1ca-11ea-8547-12c9b81e324b.png)
![image](https://user-images.githubusercontent.com/5607939/90581067-a4a2d680-e1ca-11ea-97fe-3f50e8a1919a.png)

So in conclusion, these messages are not error messages but warring/notices to make you aware of this decoupling, I realize it is not very clear, and I could probably have done a little better. So export you package with this new switch set to NO, and this notice should go away.

in the mean wile I can see that we may need to remove these component ID's without giving a notice, yet this is not that easy since the function that updates and generates this notice is the same function used for all ID remapping. But you can take a look at [this moment on line 2209](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/import_joomla_components.php#L2209) which calls [setNewID](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/models/import_joomla_components.php#L1397)(...) and remaps the IDs of the components, modules and plugins that use this language string. Should you have an idea to improve this please make a pull request.

**Comment by Llewellynvdm** [comment] 2020-08-26 23:20
Please let me know once you have any more feedback on this, until then I am closing this.

**Closed by Llewellynvdm** 2020-08-26 23:20 UTC
