### ISSUE TITLE
Package Import VDM URL does not exist on WAMP

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#327] opened 2018-08-01 16:06 UTC
### Steps to reproduce the issue

I'm trying to follow along with the latest (short) Hello World tutorial video and trying to import the Hello World package.

- go to JCB Dashboard
- Import JCB Packages 
### Expected result

Shows a VDM tab where I can import the Hello World package

### Actual result

there is no VDM tab (just "Upload", "Directory", and "URL").

Additionally I have the following errors displayed on the page:

> Error
> The url (https://api.github.com/repos/vdm-io/JCB-Packages/git/trees/master) set to retrieve the packages does not exist!
> The url (https://api.github.com/repos/vdm-io/JCB-Community-Packages/git/trees/master) set to retrieve the packages does not exist!

### System information (as much as possible)
- OS Name & Version:  WAMP
- MySql Version:  5.5.56
- Apache Version:  2.4.27
- PHP Version: 7.1.9
- Joomla Version: 3.8.5
- JCB Version: 2.8.5
- Browser: Chrome

### Additional comments

I also tried to access by going to 
- Joomla Components
- Click 'Import JCB Packages' button 

Still not showing VDM tab (and same error).

I've tried this on several different Joomla sites (all on the WAMP).

However, trying it on a site that is on our hosting companies server (i.e. hosted) IS working properly.

Is there a Joomla setting that may be blocking this from accessing the VDM github URL (or possibly WAMP settings)? [The WAMP sites are able to access other online resources]

**Comment by Llewellynvdm** [comment] 2018-08-02 00:52
@cpaschen I have not used WAMP in many years, so I can't help you with WAMP. 

What I can say this is a network problem, and it is not with Joomla or JCB, but with possibly a PHP issue... the method we use to get values are called [getFileContents](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/admin/helpers/componentbuilder.php#L2447) and it uses two PHP functions, **curl** and **file_get_contents**. 

It first tries to use _file_get_contents_ and then _curl_... it could be that both these functions are unavailable. So check that out, other then that those **urls** and those **methods** has no limitations whatsoever.

If those functions are on, then the next would be your local network, it could be that there is no connection, this will be a WAMP or Windows issue. Search their forums or Stackoverflow for help on this.

I am closing this issue, but if you need any more help or where able to resolve it, please let me know.

**Closed by Llewellynvdm** 2018-08-02 00:52 UTC

**Comment by cpaschen** [comment] 2018-08-02 15:59
Just as a follow-up ... (for anyone reading this later) ... I was not able to get WAMP to connect (even after ensuring that curl was enabled).
Instead I installed the Bitnami Joomla package onto the same windows machine and everything worked fine. So there is obviously something within WAMP and not worth the effort to try to track down.
If someone happens to run-across this issue and a solution later please share the solution.

**Comment by derakhshana** [comment] 2020-09-30 03:21
The problem is for https certificates.
you can add this two line in every were that JCB need to check https://github.com/vdm-io... web address:
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
in the JCB component. like this:
public static function urlExists($url)
	{
		$exists = false;
		// check if we can use curl
		if (function_exists('curl_version'))
		{
			// initiate curl
			$ch = curl_init($url);
			// CURLOPT_NOBODY (do not return body)
			curl_setopt($ch, CURLOPT_NOBODY, true);
			curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
			curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
			// make call
			$result = curl_exec($ch);
Or use this instruction to say the curl to use certificate verification repo:
https://snippets.webaware.com.au/howto/stop-turning-off-curlopt_ssl_verifypeer-and-fix-your-php-config/
