### ISSUE TITLE
Admin site - Error 0 by params in edit.php

### ISSUE THREAD

**Issue by PowerAmbroz** [vdm-io/Joomla-Component-Builder#577] opened 2020-07-07 08:41 UTC
### Steps to reproduce the issue
I've edited the component and changed some things like the name of the com_, and when I installed the component, went to add something got the error:
( ! ) Notice: Undefined property: TestViewTest::$params in joomla\administrator\components\com_test\views\test\tmpl\edit.php on line 29

### Expected result
I expected that after the new version is installed there won't be any problem

### Actual result
( ! ) Notice: Undefined property: TestViewTest::$params in joomla\administrator\components\com_test\views\test\tmpl\edit.php on line 29

### System information (as much as possible)
- OS Name & Version: Win 10
- MySql Version: MariaDB 10.4.10
- Apache Version: 2.4.41
- PHP Version: 7.2.31
- Joomla Version: 3.9.3
- JCB Version: newest
- Browser: firefox

**Comment by Llewellynvdm** [comment] 2020-07-07 19:14
I need more information, there are very many places the component name is used, and in the GUI you hardly ever work with the com_ value, so please give me more details of exactly what you are trying to do.

**Comment by Llewellynvdm** [comment] 2020-07-07 19:14
Screenshots will always make things clearer.

**Comment by PowerAmbroz** [comment] 2020-07-08 06:11
Here you go. This error pops up when I go from the Admin site to add a new thing in the created component
![edit_error](https://user-images.githubusercontent.com/9193428/86883637-943f0c80-c0f2-11ea-8ce9-00f1bfc323c7.jpg)

**Comment by Llewellynvdm** [comment] 2020-07-08 14:00
You said you renamed the component? did you uninstall the previous component and reinstall the renamed one after?
Renaming a component is a major action which results in a complete new component in Joomla. So first uninstall your original component and reinstall the renamed (new) component to make sure there is no possible issues.

The screenshots I was hopping to see is what you did and where you clicked and then what happened, you just gave me the what happened part, but I have no real idea if your explanation you gave should be understood this way or that way. JCB has a whole world of different paths and for me to best help you I need to understand the exact path you took.

So from the error I see it is component related and possible nothing to-do with JCB itself directly. The github issues are not for component being build with JCB, but bugs and errors in JCB itself. Not that I am not willing to check out your issue, but I have build hundreds of component, and from what I hear many other has done the same. So JCB works and it work very well, so I assume this is a error caused by using JCB in a wrong way, and should be easy to resolve. How many of the tutorials have you watched? There is this new series that has been reported to be very helpful: https://www.youtube.com/playlist?list=PLQRGFI8XZ_wv5rgdUa31tMybFvjqCzprA

Then lastly renaming a component is easy, but if you have made changes to the code, custom code and stuff then it not easy at all and in fact to be avoided.

**Comment by PowerAmbroz** [comment] 2020-07-09 07:16
The error shows even when I delete the component from joomla and the database, delete JCB, clear cache. Then I installed JCB, created a new component with the same name, let;s say test, install it and the error still shows after going to the component on the admin site and click add test.
I don't know if it is just a component problem or a JCB problem, but it is strange to me that after uninstalling the error still shows up. 
Thanks a lot for the new videos, will watch tem soon.
Have a nice day/night.

**Comment by Llewellynvdm** [comment] 2020-07-18 03:44
hmmm that just does not sound right at all. There must be another issue, seeing that we have literally thousands of users and I have not heard or seen this before. Have you tried a [bitnami stack as your development environment](https://www.youtube.com/watch?v=zpS52k89YcI&list=PLQRGFI8XZ_wtGvPQZWBfDzzlERLQgpMRE&index=73&t=0s)?

**Comment by Llewellynvdm** [comment] 2020-07-18 03:47
This will at least make sure we are in the same world... and can be sure your environment is more or less like mine. Since JCB has been maintained in a [Bitnami](https://bitnami.com/stack/joomla/installer) stack for the last few years.

**Comment by Llewellynvdm** [comment] 2020-07-28 14:44
Any more info here? I am closing this until we get more feedback.

**Closed by Llewellynvdm** 2020-07-28 14:44 UTC
