### ISSUE TITLE
Module builder issue: postflight install wrong comment code

### ISSUE THREAD

**Issue by jcodewalker** [vdm-io/Joomla-Component-Builder#570] opened 2020-06-12 09:09 UTC
### Steps to reproduce the issue
add code in postflight install field

### Expected result
JCB comment code using php tags: /***jcbcomment***/

### Actual result
JCB comment added using html tags

Obviusly it's not possible to install it as is.

### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: 
- PHP Version: 
- Joomla Version: 
- JCB Version: 2.10.13
- Browser:

**Comment by jcodewalker** [comment] 2020-06-12 09:12
Ok, it seems fixed in the latest release.

**Comment by jcodewalker** [comment] 2020-06-17 15:17
No, still there in version 2.11.2

**Comment by Llewellynvdm** [comment] 2020-06-17 20:23
Can you please give me a picture "screenshot" of this in the code and the JCB GUI.

**Comment by Llewellynvdm** [comment] 2020-07-06 08:55
No reply in 19 days so I assume issue is resolved, let me know if you have any further questions.

**Comment by jcodewalker** [comment] 2020-07-06 12:35
No reply to what?
You didn’t announced any update…

**Comment by Llewellynvdm** [comment] 2020-07-06 21:34
I asked the following question:

> Can you please give me a picture "screenshot" of this in the code and the JCB GUI.

Yet after 19 days I did not hear back from you with more details. So unless you give me enough details I can't reproduce the issue, so if I ask for more details, pictures, screenshots and actual code, then it means I can't fix this issue with the current information provided. So just from the start give me enough information, and we will have a better, and shorted path to resolving the issue.

**Comment by jcodewalker** [comment] 2020-07-07 05:56
![Schermata 2020-07-07 alle 07 51 28](https://user-images.githubusercontent.com/49115855/86722405-24b01b00-c027-11ea-9442-54b9b50c0c60.png)
As you can see I sent you the image 25 days ago.
Please, use a more steady system to manage issues.

**Comment by Llewellynvdm** [comment] 2020-07-07 12:49
@jcodewalker you are just so funny, you crack me up lol.

Github is used by Joomla, and will continue to be used for JCB. Maybe you should just go to [github](https://github.com/vdm-io/Joomla-Component-Builder/issues/570), like I do every time for you, and comment directly on the feed when images are ask for.

I will now look in to the issue, thank you for giving me the details.

**Comment by Llewellynvdm** [comment] 2020-07-07 19:43
Should be fixed now, please check and let me know.

**Closed** 2020-07-07 19:42 UTC

**Comment by jcodewalker** [comment] 2020-07-13 17:00
Yes, fixed, confirm.
Thanks
