### ISSUE TITLE
Calander field not working

### ISSUE THREAD

**Issue by Schrijvers123** [vdm-io/Joomla-Component-Builder#331] opened 2018-08-14 19:23 UTC
### Steps to reproduce the issue
Add a calander field

### Expected result
A calender in the backend of the componentn

### Actual result
Error during installation:
CREATE TABLE IF NOT EXISTS `#__trainershub_training` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`alias` CHAR(64) NOT NULL DEFAULT '',
	`mytextblock` TEXT NOT NULL,
	`startdate` DATETIME NOT NULL DEFAULT '',
	`trainingname` VARCHAR(255) NOT NULL DEFAULT '',
	`params` text NOT NULL DEFAULT '',
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`access` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	`metakey` TEXT NOT NULL DEFAULT '',
	`metadesc` TEXT NOT NULL DEFAULT '',
	`metadata` TEXT NOT NULL DEFAULT '',
	PRIMARY KEY  (`id`),
	KEY `idx_access` (`access`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_trainingname` (`trainingname`),
	KEY `idx_alias` (`alias`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;

Whatever I change in the field, it still give always this error. It seems default value is not taken (even if I change it).

PLease help!
### System information (as much as possible)
- OS Name & Version: Windows 10
- MySql Version: 5.5.5-10.1.35-MariaDB-1~xenial 
- Apache Version: 
- PHP Version: 7.1.20 
- Joomla Version: Joomla! 3.8.11 Stable [ Amani ] 31-July-2018 14:00 GMT 
- JCB Version: 2.8.5
- Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by peterpetrov** [comment] 2018-08-14 19:30
Hello Arjen. Can you give us the error please? There should be something about which part of the query is failing.

**Comment by peterpetrov** [comment] 2018-08-14 19:37
Thanks. The thing is that DATETIME field need to have default value exactly as '0000-00-00 00:00:00'. That is something to do with MariaDB. All fields that are calendar need to have custom default value exactly as the one i gave you. I suspected it from the beginning. Had issues myself before i found the exact resolution. Change that and let me know if that works for you.

Peter

**Comment by Schrijvers123** [comment] 2018-08-14 20:00
What ever I enter as default vauevit is mot showrd up.

Arjen Schrijvers
Eigenaar SCHRIJVERS123.NL


Op 14 aug. 2018 om 21:37 heeft peterpetrov <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Thanks. The thing is that DATETIME field need to have default value exactly as '0000-00-00 00:00:00'. That is something to do with MariaDB. All fields that are calendar need to have custom default value exactly as the one i gave you. I suspected it from the beginning. Had issues myself before i found the exact resolution. Change that and let me know if that works for you.

Peter

**Comment by peterpetrov** [comment] 2018-08-14 20:04
Is this a new table you are creating?

**Comment by Schrijvers123** [comment] 2018-08-14 20:37
Yep.

Arjen Schrijvers
Eigenaar SCHRIJVERS123.NL


Op 14 aug. 2018 om 22:07 heeft peterpetrov <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Is this a new table you are creating?

**Comment by peterpetrov** [comment] 2018-08-14 20:44
You can drop the table (if already created) and delete that particular sql update in the component section. Then try again to install it.

**Comment by Schrijvers123** [comment] 2018-08-14 20:50
Hi Peter,

That’s the problem, due to the error it is not making the table.

Best regards,

Arjen

Van: peterpetrov <notifications@github.com>
Verzonden: dinsdag 14 augustus 2018 22:45
Aan: vdm-io/Joomla-Component-Builder <Joomla-Component-Builder@noreply.github.com>
CC: Arjen Schrijvers <arjen@schrijvers123.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [vdm-io/Joomla-Component-Builder] Calander field not working (#331)


You can drop the table (if already created) and delete that particular sql update in the component section. Then try again to install it.

**Comment by peterpetrov** [comment] 2018-08-14 20:54
Just looked at my calendar values. Try to change it to just DATE and default to Other Default '0000-00-00'. Please see the image attached.
![screen shot 2018-08-14 at 23 51 59](https://user-images.githubusercontent.com/2786810/44117950-5fe51058-a01d-11e8-9e19-25844931eaa3.png)

**Comment by Schrijvers123** [comment] 2018-08-14 21:04
I foudn the issue. It treid to complied a new version (1.0.32). But in the version before, the table was build. That one I update manually.

TO do, got to Joomla Components and click on the Green button named ‘Edit component updates for this Joomla component’ (block 1 in picture below).
[cid:image003.jpg@01D43423.19B614D0]

You will see al update sql queries. The last version was (is) 1.0.31 and there was the error.
[cid:image004.jpg@01D43423.19B614D0]
For some reason it was not updating that part.

I remember that the first time I compiled it I set the default value wrong. Sencond time I changed it, but Component Builder didn’t recognized it.

Issue solved.

Thanks for your help Peter.

Best regards,


Arjen Schrijvers
Eigenaar SCHRIJVERS123.NL

[cid:image001.png@01D240C9.58A72980]


Postadres: Turkooisdreef 21, 7828 BJ Emmen | Bezoekadres: Dokter van Deenweg 108 (kamer 245/246), 8025 BK Zwolle 
Tel:  +31 591 532 116|  Fax: +31 84 8328282 | Mobile: +31 628 022 567 
KVK-nummer: 24376300 | BTW-nummer: Staat op onze offertes, overeenkomsten en facturen.

This e-mail is confidential and may be privileged. It may be read, copied and used only by the intended recipient.  If you have received it in error, please contact the sender immediately by return e-mail or by telephoning +31 591 532116.  Please then delete the e-mail and do not disclose its contents to any person. SCHRIJVERS123.NL believes, but does not warrant that this e-mail and any attachments, are virus free. You should take full responsibility for virus checking.  SCHRIJVERS123.NL reserves the right to monitor all email communications through its internal and external networks.



Van: peterpetrov <notifications@github.com>
Verzonden: dinsdag 14 augustus 2018 22:55
Aan: vdm-io/Joomla-Component-Builder <Joomla-Component-Builder@noreply.github.com>
CC: Arjen Schrijvers <arjen@schrijvers123.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [vdm-io/Joomla-Component-Builder] Calander field not working (#331)


Just looked at my calendar values. Try to change it to just DATE and default to Other Default '0000-00-00'. Please see the image attached.
[screen shot 2018-08-14 at 23 51 59]<https://user-images.githubusercontent.com/2786810/44117950-5fe51058-a01d-11e8-9e19-25844931eaa3.png>

**Comment by peterpetrov** [comment] 2018-08-14 21:05
Nice. Issue solved?

**Comment by Schrijvers123** [comment] 2018-08-14 21:07
Yes, but of still wondering why it was not updates automatically:

Arjen Schrijvers
Eigenaar SCHRIJVERS123.NL


Op 14 aug. 2018 om 23:06 heeft peterpetrov <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Nice. Issue solved?

**Comment by peterpetrov** [comment] 2018-08-14 21:18
I would be really gambling with the answer here. MariaDB is just a bit different and there is the requirement to fine tune and get used to the relationship between JCB and MariaDB. Any other saying can be incorrect but i think there is something with the sql updates when you got the defaults on a datetime field wrong on the first attempt. When i found  how to fix it i stopped going further because my system is not the most common one and i left it there.

**Comment by Schrijvers123** [comment] 2018-08-14 21:25
It has nothing todo with MariaDB.

When you set the first time de defaults wrong, compiled the version. You get (as expected) the error.
When you set the default proper, and recompiled the component, JCB is still thing that nothing has changed and is trying to build the old version.

On this moment, for me the only option was to change it manually.

I need to build more tables and will see if I can reproduce it.

To be short, it seems to be a bug, but there is a workaround.

Best regards,

Arjen Schrijvers
Eigenaar SCHRIJVERS123.NL

[cid:image001.png@01D240C9.58A72980]


Postadres: Turkooisdreef 21, 7828 BJ Emmen | Bezoekadres: Dokter van Deenweg 108 (kamer 245/246), 8025 BK Zwolle 
Tel:  +31 591 532 116|  Fax: +31 84 8328282 | Mobile: +31 628 022 567 
KVK-nummer: 24376300 | BTW-nummer: Staat op onze offertes, overeenkomsten en facturen.

This e-mail is confidential and may be privileged. It may be read, copied and used only by the intended recipient.  If you have received it in error, please contact the sender immediately by return e-mail or by telephoning +31 591 532116.  Please then delete the e-mail and do not disclose its contents to any person. SCHRIJVERS123.NL believes, but does not warrant that this e-mail and any attachments, are virus free. You should take full responsibility for virus checking.  SCHRIJVERS123.NL reserves the right to monitor all email communications through its internal and external networks.


Van: peterpetrov <notifications@github.com>
Verzonden: dinsdag 14 augustus 2018 23:19
Aan: vdm-io/Joomla-Component-Builder <Joomla-Component-Builder@noreply.github.com>
CC: Arjen Schrijvers <arjen@schrijvers123.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [vdm-io/Joomla-Component-Builder] Calander field not working (#331)


I would be really gambling with the answer here. MariaDB is just a bit different and there is the requirement to fine tune and get used to the relationship between JCB and MariaDB. Any other saying can be incorrect but i think there is something with the sql updates when you got the defaults on a datetime field wrong on the first attempt. When i found how to fix it i stopped going further because my system is not the most common one and i left it there.

**Comment by Llewellynvdm** [comment] 2018-08-15 17:51
Hi, this is not a bug, JCB does not update the SQL in the Component Updates area to avoid breaking any custom SQL you may have place there.

So yes if you make a mistake with the date default value, you need to go and manually fix it in the Component Updates area. I have spend a lot of time thinking how to do revers engineering on the values. But this is not as easy as it sounds.... there is just to much in play.

So the manual work around is the best we have. The only other fix I could add is to force date default values to `0000-00-00 00:00:00` but this could become an issue for those who only want the date and not the time. Hmmm so best answer is to get it right... I mean the defaults :+1:

**Comment by Llewellynvdm** [comment] 2018-08-15 17:53
If you have any ideas, please share them, if not then this issue is resolved and you can close the issue.

**Comment by Schrijvers123** [comment] 2018-08-15 17:56
Isn’t it an option that if you change a default value that the sql is also changed?

Best regards.

Arjen Schrijvers
Eigenaar SCHRIJVERS123.NL


Op 15 aug. 2018 om 19:54 heeft <<ewe>>yn <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


If you have any ideas, please share them, if not then this issue is resolved and you can close the issue.

**Comment by peterpetrov** [comment] 2018-08-15 17:57
As for date sql field only on MariaDB you can just put the date section. But it is manual work as well. I think the best option is to document it and advertise it as is.

Peter

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Closed** 2018-08-15 19:41 UTC

**Comment by Llewellynvdm** [comment] 2018-08-15 20:58
Yes it does change the sql in the install.mysql.utf8.sql file gets updated, but since the **update sql** is already set and the history **moment has past**, so JCB does not see a change in the field when you change the default, so it does not trigger a new sql update, and even if it did, the previous update had an error and must be remove, or fixed manually.

This issue is just related to the auto updating sql that gets generated with new fields/columns or views/tables are found, or when big changes are made to fields/columns or views/tables.

This is a feature that requires a little hands on if things go wrong... simply because it is event driven... when a change in history of the component development is detected, this even is only detected once, and then changes are made automatically by JCB to your sql update area.

Yes we can deepen this feature I suppose... but it is already very powerful, and normally works so well that developers do not even know it is there, how it works, and yet every things just works.

But as with all automatic features there is a kind of mystery of what is being done behind the scene. So yes we should formulate a manual for JCB and we should document this area slowly and clearly.

**Comment by Schrijvers123** [comment] 2018-08-15 21:03
I totally agree. It will be more work to find a proper solution (that fits in every situation) the document it properly.

Document it, is the best solution.

Best regards,

Arjen Schrijvers


Van: <<ewe>>yn <notifications@github.com>
Verzonden: woensdag 15 augustus 2018 22:58
Aan: vdm-io/Joomla-Component-Builder <Joomla-Component-Builder@noreply.github.com>
CC: Arjen Schrijvers <arjen@schrijvers123.nl>; State change <state_change@noreply.github.com>
Onderwerp: Re: [vdm-io/Joomla-Component-Builder] Calander field not working (#331)


Yes it does change the sql in the install.mysql.utf8.sql file gets updated, but since the update sql is already set and the history moment has past, so JCB does not see a change in the field when you change the default, so it does not trigger a new sql update, and even if it did, the previous update had an error and must be remove, or fixed manually.

This issue is just related to the auto updating sql that gets generated with new fields/columns or views/tables are found, or when big changes are made to fields/columns or views/tables.

This is a feature that requires a little hands on if things go wrong... simply because it is event driven... when a change in history of the component development is detected, this even is only detected once, and then changes are made automatically by JCB to your sql update area.

Yes we can deepen this feature I suppose... but it is already very powerful, and normally works so well that developers do not even know it is there, how it works, and yet every things just works.

But as with all automatic features there is a kind of mystery of what is being done behind the scene. So yes we should formulate a manual for JCB and we should document this area slowly and clearly.
