### ISSUE TITLE
Error - getNode(1,) failed

### ISSUE THREAD

**Issue by cpaschen** [vdm-io/Joomla-Component-Builder#277] opened 2018-05-04 23:23 UTC
### Steps to reproduce the issue

Compile any component and install
OR
Install ANY Joomla extension (from any source)

### Expected result

Component should install without errors

### Actual result

Error
Joomla\CMS\Table\Menu::_getNode(1, ) failed.
Warning
Error building Administrator Menus.
Message
Installation of the component was successful.

### System information (as much as possible)
- OS Name & Version: WAMP
- MySql Version:  5.7.19
- Apache Version: 2.4.27
- PHP Version: 7.1.9
- Joomla Version: 3.8.7
- JCB Version: 2.4.8 Beta Release
- Browser: Chrome

### Additional comments

Although this is obviously a core issue, this happened after making a change to a component (I added a custom admin menu). I've deleted that custom menu, but the problem continues.

I did NOT make any manual changes to any files from the time it was working properly to when it broke. Only made the UI changes on JCB related to adding a custom admin menu.

The extension DOES get compiled and installed properly, but there is no admin menu for that component.

Manual Fix: Add record in the _menu table with id 1. Then all installation works again.

[Because the problem initially happened when I compiled and installed from JCB I'm wondering if this could be caused by JCB. I've never seen this happen before so not sure what caused it.]

I realize that this a VERY strange occurance. I couldn't reproduce it, even when adding and removing a custom admin menu again.

I'm just reporting it here in case you know exactly what might be happening and that it is a bug.
Otherwise, feel free to just close this as an unverified/unreproduceable isssue.

**Comment by Llewellynvdm** [comment] 2018-05-05 00:33
Thanks for the heads-up, we close the issue for now. If it comes up again, or if someone else has the same issue with more details to reproduce... we open this up again... and fix it.

For now I think it could be bad timing or coincidence... since I have only once seen an error like this, and that was before JCB existed... it was a Joomla upgrade glitch at the time, and we also had to manually update the DB to fix it.

**Comment by oriolun** [comment] 2019-01-29 19:12
Got the same issue. You can reproduce it with these steps:
1) Menu manager
2) Create new menu for backend area.
3) Create new custom admin view
4) Compile component
5) Install
6) Error.

**Comment by Llewellynvdm** [comment] 2019-01-29 23:17
I take it you are also on WAMP? With the same system settings.

**Comment by oriolun** [comment] 2019-02-02 21:42
> 
> 
> I take it you are also on WAMP? With the same system settings.

No, it's a remote server.

    MySql Version: 5.7
    PHP Version: 7.2
    Joomla Version: 3.9.2
    JCB Version: latest
    Browser: Firefox

**Comment by Llewellynvdm** [comment] 2020-04-26 16:57
Any resolve to this with the last few updates? I have never been able to reproduce this, so if it comes up, please add more details here and I will open the issue again.

**Closed by Llewellynvdm** 2020-04-26 16:57 UTC
