### ISSUE TITLE
I can't add fields in an existing admin view

### ISSUE THREAD

**Issue by ewmwollmann** [vdm-io/Joomla-Component-Builder#414] opened 2019-05-06 11:47 UTC
### System information (as much as possible)
- OS Name & Version: 
- MySql Version: 
- Apache Version: Apache/2.4.25
- PHP Version: 7.2.15
- Joomla Version: 3.9.2
- JCB Version: 2.9.14
- Browser: Firefox 66.0.3

### Additional comments

I created a new component which is working. Now I want add more fields in the admin and site view. I go in edit admin view, but when I click in the plus button, nothing happened. It doesn't add a new row.
I didn't find any answer to this. Can someone help me?
Thx in advance.
Simone

**Comment by ewmwollmann** [comment] 2019-05-06 12:44
I tried now to create a new admin view but in general I can't add more than one field in there. The plus button doesn't work.

**Comment by Llewellynvdm** [comment] 2019-05-06 16:38
Please give me a few screen shots.

**Comment by ewmwollmann** [comment] 2019-05-07 05:45
Please find enclosed
![screen-JCB](https://user-images.githubusercontent.com/45290472/57274547-e83c0480-709b-11e9-82bf-fe4b204ca552.JPG)
![screen-JCB0](https://user-images.githubusercontent.com/45290472/57274548-e8d49b00-709b-11e9-986f-b93d4e785b87.JPG)
![screen-JCB1-2](https://user-images.githubusercontent.com/45290472/57274549-e8d49b00-709b-11e9-96cc-217497210eec.JPG)
![screen-JCB1-1](https://user-images.githubusercontent.com/45290472/57274550-e8d49b00-709b-11e9-987b-69d8d4aacdd5.JPG)
![screen-JCB1](https://user-images.githubusercontent.com/45290472/57274552-e8d49b00-709b-11e9-89e0-772fa4359ea9.JPG)

**Comment by ewmwollmann** [comment] 2019-05-07 05:48
I deinstalled and installed the JCB again. But it is the same. I start completely in the beginning:
Add new fields, create new admin view, save first before I tried to add fields, but after the first field I can't add more by clicking the +button.

**Comment by Llewellynvdm** [comment] 2019-05-07 09:02
Okay first thing here, the subform used there is not really JCB, since it is a pure Joomla subfrom implementation, and not wanting to add more rows must be due to a JavaScript issue in your browser.

IF you can open the inspect element browser debugging area, and check what happens in the console when you click that plus, since I suspect there is a issue with the browser, have you tried another PC, or browser?

JCB does not build the JavaScript for that adding row feature, it is Joomla generated.

**Comment by ewmwollmann** [comment] 2019-05-07 12:02
Yes, is the same in other browser.
enclosed 
[subform_repeatable.txt](https://github.com/vdm-io/Joomla-Component-Builder/files/3152469/subform_repeatable.txt)

the subform js

**Comment by Llewellynvdm** [comment] 2019-05-07 13:18
@ewmwollmann there really not much I can do to help you here, it works in thousands of other users environments and browsers. So I can reproduce your issue, and can not debug it really.

If you want me to help you with teamviewer, or some other support tool, then let me know in private message. I will close this issue simply because it is not related to JCB, since like I said before, it is a Joomla produced field type, that really works well for many many other users.

Therefore it must be related to your setup, sorry that I can't help you more :+1: 

You welcome to continue communicate on this issue if you have more questions in relation to resolving it. We have never seen this happen before, Joomla's subform implementation is fairly solid.

**Closed by Llewellynvdm** 2019-05-07 13:18 UTC
