### ISSUE TITLE
Unable to add rows (e.g. to create a new Site View)

### ISSUE THREAD

**Issue by nickkraakman** [vdm-io/Joomla-Component-Builder#398] opened 2019-03-14 16:06 UTC
### Steps to reproduce the issue
Navigate to the JCB component in the Joomla backend. Edit a component, then go to the `Site Views` tab and click `Create`. If you now click the `+` button to add a new row to the site views list, nothing happens, apart from the following console error:

```
Uncaught TypeError: e.parseHTML is not a function
    at e.subformRepeatable.addRow (subform-repeatable.js?7653fe41a06dd8f89aed8e5cec0590a3:1)
    at HTMLAnchorElement.<anonymous> (subform-repeatable.js?7653fe41a06dd8f89aed8e5cec0590a3:1)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.i (jquery.min.js:3)
```

### Expected result
The expected result is that a new row is added and no error is shown.

### System information
- OS Name & Version: OSX 10.14.2
- MySql Version: 5.6.37
- Apache Version: 2.4.27
- PHP Version: 7.1.8
- Joomla Version: 3.9.4
- JCB Version: 2.9.11
- Browser: Chrome 72

**Comment by Llewellynvdm** [comment] 2019-03-18 19:26
Hmmm did you watch the tutorials... since your work flow sounds a little different from what I am use to.

I usually first create the fields, then add them to views, then add the views to components. This is the best approach really. Not from the component side down to the field... but fields first, then views, then components. Once they are lined up then you can traverse them in any direction, but with the initial setup I work from the ground up.

Okay so having said that... what you explained should also work. Lets see is the component saved? and does the site-view already exist?

Again first create the site-view as that part requires a dynamicGet to be created first, then the site-view and then add it to a component.

Do note there is a difference in adding a site-view to a component and creating one.

To me it seems like more tutorial time is needed :) but okay it could be that you have a bug, I am just not seeing the same error. So give me some screen shots and more info if the above does not help.

**Comment by Llewellynvdm** [comment] 2019-03-22 21:58
If you have any more comments just post them here, even if the issue is closed.

Since we are closing this until you give use more feedback.

**Closed by Llewellynvdm** 2019-03-22 21:58 UTC
